#!/bin/bash
#PBS -l nodes=12:ppn=12
#PBS -l walltime=00:05:00
#PBS -q batch
#PBS -N with_balance
#PBS -j oe
cd ~/PA4
mpiexec -np 12 --map-by ppr:1:node --hostfile $PBS_NODEFILE ./PA4.cx 100000000 100000
